mysql:
  user: "root"
  password: "156156qQ"
  database: "tiktokk"
  ip: "localhost"
  port: 3306
  config: "charset=utf8mb4&parseTime=true&loc=Local"
  log-level: 4 # GORM Tlog level, 1: silent, 2:error, 3:warn, 4:info

jwt:
  key: "666"
  identityKey: "username"

feed:
  len: 3

fileSave:
  file: "http://192.168.31.30:10001/publicSrc/"
  uploads : "http://192.168.31.30:10001/uploads/"

log:
  level: log
  disableCaller: true
  disableStackTrace: false
  format: console
  outputPaths: [./tiktokk.log,stdout]
  errorOutputPaths: [stderr]
