mysql:
  dsn: "root:156156qQ@tcp(127.0.0.1:3306)/TikTokk?charset=utf8mb4&parseTime=true&loc=Local"

jwt:
  key: "666"
  identityKey: "username"

feed:
  len: 3

fileSave:
  path: "http://192.168.31.29:6666/"