mysql:
  user: "root"
  password: "156156qQ"
  database: "TikTokk"
  ip: "192.168.31.29"
  port: 3306
  config: "charset=utf8mb4&parseTime=true&loc=Local"
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

jwt:
  key: "666"
  identityKey: "username"

feed:
  len: 3

fileSave:
  path: "http://192.168.31.29:6666/PublicSrc/"